import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import javax.swing.JOptionPane;
/**
 *
 * @author scher
 */
public class EmployeesMenuGUI extends javax.swing.JFrame {
    private Hotel hotel;
    private Map<Integer, Employee> employees;
    private static final String filename = "employees.csv";
    private static final String delimiter = ",";

    /**
     * Creates new form EmployeesMenuGUI
     */
    public EmployeesMenuGUI() {
        initComponents();
    }
    public EmployeesMenuGUI(Hotel hotel){
        initComponents();
        this.hotel = hotel;
        txtEditFirstname.setVisible(false);
        txtEditLastname.setVisible(false);
        txtEditPassword.setVisible(false);
        txtEditPayrate.setVisible(false);
        txtEditShiftDuration.setVisible(false);
        txtEditEmail.setVisible(false);
        lblEditFirstname.setVisible(false);
        lblEditLastname.setVisible(false);
        lblEditPassword.setVisible(false);
        lblEditPayrate.setVisible(false);
        lblEditEmail.setVisible(false);
        btnEdit.setVisible(false);
        lblEditShiftDuration.setVisible(false);
        employees = hotel.getEmployees();
    }
    private void readCSV()
    {
        try
        {
        File file = new File(filename);
        FileReader fr = new FileReader(file);
        BufferedReader br = new BufferedReader(fr);
        
        String line = "";
        String[] tempArr;
        while((line = br.readLine()) != null)
        {
            tempArr = line.split(delimiter);
            for(String field : tempArr)
            {
                System.out.println(field + "");
            }
            String firstname = tempArr[0];
            String lastname = tempArr[1];
            String password = tempArr[2];
            Double payrate = Double.valueOf(tempArr[3]);
            
            Employee employee = new Employee(firstname, lastname, password, payrate);
            hotel.addEmployee(employee);
        }
        br.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error reading the file.", "ERROR", HEIGHT);
        }
    }
    private void updateCSV()
    {
        try
        {
            File file = new File(filename);
            BufferedWriter bf = new BufferedWriter(new FileWriter(file));
            
            for(Map.Entry employee : employees.entrySet())
            {
                String row = "";
                int employeeID = (Integer)employee.getKey();
                Employee emp = employees.get(employeeID);
                
                String firstname = emp.getFirstName();
                String lastname = emp.getLastName();
                String password = emp.getPassword();
                double payrate = emp.getPayRate();
                
                row = firstname + "," + lastname + "," + password + "," + String.valueOf(payrate) + "\n";
                bf.write(row); 
            }
            bf.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error reading the file.", "ERROR", HEIGHT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalPanel = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        txtAddFirstName = new javax.swing.JTextField();
        txtAddLastName = new javax.swing.JTextField();
        txtAddPassword = new javax.swing.JTextField();
        txtAddPayrate = new javax.swing.JTextField();
        lblAddFirstName = new javax.swing.JLabel();
        lbllAddLastName = new javax.swing.JLabel();
        lblAddPassword = new javax.swing.JLabel();
        lblAddPayrate = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        removePanel = new javax.swing.JPanel();
        lblRemoveID = new javax.swing.JLabel();
        txtIDToRemove = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        lblSearchID = new javax.swing.JLabel();
        txtIdToSearch = new javax.swing.JTextField();
        btnSearchID = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        lblidToEdit = new javax.swing.JLabel();
        txtIDToEdit = new javax.swing.JTextField();
        lblEditFirstname = new javax.swing.JLabel();
        txtEditFirstname = new javax.swing.JTextField();
        lblEditPayrate = new javax.swing.JLabel();
        txtEditPayrate = new javax.swing.JTextField();
        lblEditPassword = new javax.swing.JLabel();
        txtEditPassword = new javax.swing.JTextField();
        lblEditLastname = new javax.swing.JLabel();
        txtEditLastname = new javax.swing.JTextField();
        lblEditShiftDuration = new javax.swing.JLabel();
        txtEditShiftDuration = new javax.swing.JTextField();
        btnSearchIDToEdit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblEditEmail = new javax.swing.JLabel();
        txtEditEmail = new javax.swing.JTextField();
        viewAllPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaShowAll = new javax.swing.JTextArea();
        btnShowAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employees Menu");

        generalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalPanelMouseClicked(evt);
            }
        });

        txtAddFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddFirstNameActionPerformed(evt);
            }
        });

        txtAddLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLastNameActionPerformed(evt);
            }
        });

        lblAddFirstName.setText("First Name");

        lbllAddLastName.setText("Last Name");

        lblAddPassword.setText("Password");

        lblAddPayrate.setText("Payrate");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddFirstName)
                            .addComponent(lbllAddLastName)
                            .addComponent(lblAddPayrate)
                            .addComponent(lblAddPassword)
                            .addComponent(txtAddLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtAddFirstName)
                            .addComponent(txtAddPassword))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(txtAddPayrate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(113, 113, 113))))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAddFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbllAddLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddPayrate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddPayrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        generalPanel.addTab("Add", addPanel);

        lblRemoveID.setText("Enter employee ID to remove:");

        txtIDToRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDToRemoveActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove)
                    .addComponent(lblRemoveID)
                    .addComponent(txtIDToRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRemoveID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDToRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        generalPanel.addTab("Remove", removePanel);

        lblSearchID.setText("Enter ID of employee to search");

        btnSearchID.setText("Search");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchID)
                    .addComponent(txtIdToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchID))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblSearchID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchID)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        generalPanel.addTab("Search", searchPanel);

        lblidToEdit.setText("ID To Edit");

        lblEditFirstname.setText("First Name");

        lblEditPayrate.setText("Payrate");

        lblEditPassword.setText("Password");

        lblEditLastname.setText("Last Name");

        lblEditShiftDuration.setText("Shift duration");

        txtEditShiftDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditShiftDurationActionPerformed(evt);
            }
        });

        btnSearchIDToEdit.setText("Search");
        btnSearchIDToEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDToEditActionPerformed(evt);
            }
        });

        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblEditEmail.setText("Email");

        txtEditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidToEdit)
                    .addComponent(txtIDToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditFirstname)
                    .addComponent(txtEditFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditPayrate)
                    .addComponent(txtEditPayrate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchIDToEdit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditLastname)
                            .addComponent(txtEditShiftDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditShiftDuration))
                        .addGap(35, 35, 35)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditPassword)
                            .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditEmail))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblidToEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchIDToEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditFirstname)
                            .addComponent(lblEditLastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(lblEditPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditPayrate)
                    .addComponent(lblEditShiftDuration)
                    .addComponent(lblEditEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPayrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditShiftDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(77, 77, 77))
        );

        generalPanel.addTab("Edit", editPanel);

        txtAreaShowAll.setEditable(false);
        txtAreaShowAll.setColumns(20);
        txtAreaShowAll.setRows(5);
        jScrollPane1.setViewportView(txtAreaShowAll);

        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewAllPanelLayout = new javax.swing.GroupLayout(viewAllPanel);
        viewAllPanel.setLayout(viewAllPanelLayout);
        viewAllPanelLayout.setHorizontalGroup(
            viewAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(viewAllPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewAllPanelLayout.setVerticalGroup(
            viewAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnShowAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        generalPanel.addTab("View All", viewAllPanel);

        getContentPane().add(generalPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddFirstNameActionPerformed

    private void txtAddLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLastNameActionPerformed

    private void txtIDToRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDToRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDToRemoveActionPerformed

    private void txtEditShiftDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditShiftDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditShiftDurationActionPerformed

    private void generalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generalPanelMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String firstName = txtAddFirstName.getText();
        String lastName = txtAddLastName.getText();
        String password = txtAddPassword.getText();
        double payrate = Double.parseDouble(txtAddPayrate.getText());
        Employee employeeToAdd = new Employee(firstName, lastName, password, payrate);
        hotel.addEmployee(employeeToAdd);
        txtAddFirstName.setText("");
        txtAddLastName.setText("");
        txtAddPassword.setText("");
        txtAddPayrate.setText("");
        String output = "Employee: " + firstName + " " + lastName + " has been added" ;
        JOptionPane.showMessageDialog(this, output, "SUCCESS", HEIGHT);
        
        updateCSV();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int idToRemove = Integer.parseInt(txtIDToRemove.getText());
        
        if(employees.get(idToRemove) instanceof Manager)
        {
            JOptionPane.showMessageDialog(this, "Cannot Remove The Manager", "ERROR", HEIGHT);
        }
        else if(employees.containsKey(idToRemove))
        {
            hotel.removeEmployee(idToRemove);
            txtIDToRemove.setText("");
            JOptionPane.showMessageDialog(this, "Employee Removed", "SUCCESS", HEIGHT);
            updateCSV();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "ID does not exist", "ERROR", HEIGHT);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        int idToSearch = Integer.parseInt(txtIdToSearch.getText());
        if(employees.containsKey(idToSearch)) // if the employee ID exists
        {
            Employee employee = employees.get(idToSearch);
            String output = "Employee: " + employee.getFirstName() + " " + employee.getLastName() + "\nID: " + idToSearch + "\nEmail: " + employee.getEmail() + "\nPay Rate: " + employee.getPayRate() +  "\nShift: " + employee.getShift() + " hrs\n";
            JOptionPane.showMessageDialog(this, output, "Employee Info", HEIGHT);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "ID does not exist", "ERROR", HEIGHT);
        }
        
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int idToEdit = Integer.parseInt(txtIDToEdit.getText());
        Employee employeeToEdit = employees.get(idToEdit);
        
        String firstName = txtEditFirstname.getText();
        String lastName = txtEditLastname.getText();
        String email = txtEditEmail.getText();
        double payRate = Double.parseDouble(txtEditPayrate.getText());
        double shiftDuration = Double.parseDouble(txtEditShiftDuration.getText());
        String password = txtEditPassword.getText();
        hotel.editEmployee(idToEdit, firstName, lastName, email, password, payRate, shiftDuration);
        
        txtIDToEdit.setText("");
        btnSearchIDToEdit.setVisible(true);
        txtEditFirstname.setText("");
        txtEditLastname.setText("");
        txtEditEmail.setText("");
        txtEditPassword.setText("");
        txtEditShiftDuration.setText("");
        txtEditPayrate.setText("");
        JOptionPane.showMessageDialog(this, "Employee Information Updated.", "SUCCESS", HEIGHT);
        
        updateCSV();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtEditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditEmailActionPerformed

    private void btnSearchIDToEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDToEditActionPerformed
        int idToEdit = Integer.parseInt(txtIDToEdit.getText());
        if(employees.containsKey(idToEdit))
        {
            Employee employeeToEdit = employees.get(idToEdit);
            txtEditFirstname.setText(employeeToEdit.getFirstName());
            txtEditLastname.setText(employeeToEdit.getLastName());
            txtEditEmail.setText(employeeToEdit.getEmail());
            txtEditPassword.setText(employeeToEdit.getPassword());
            txtEditShiftDuration.setText(Double.toString(employeeToEdit.getShift()));
            txtEditPayrate.setText(Double.toString(employeeToEdit.getPayRate()));
            txtEditFirstname.setVisible(true);
            txtEditLastname.setVisible(true);
            txtEditPassword.setVisible(true);
            txtEditPayrate.setVisible(true);
            txtEditShiftDuration.setVisible(true);
            txtEditEmail.setVisible(true);
            lblEditFirstname.setVisible(true);
            lblEditLastname.setVisible(true);
            lblEditPassword.setVisible(true);
            lblEditPayrate.setVisible(true);
            lblEditShiftDuration.setVisible(true);
            lblEditEmail.setVisible(true);
            btnEdit.setVisible(true);
            btnSearchIDToEdit.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "ID does not exist", "ERROR", HEIGHT);
        }
    }//GEN-LAST:event_btnSearchIDToEditActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        String output = "";
        for(Integer key : employees.keySet())
        {
            output += hotel.lookUpEmployeeWithReturn(key);
        }
        txtAreaShowAll.setText(output);
    }//GEN-LAST:event_btnShowAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeesMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeesMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeesMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeesMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeesMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchIDToEdit;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTabbedPane generalPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddFirstName;
    private javax.swing.JLabel lblAddPassword;
    private javax.swing.JLabel lblAddPayrate;
    private javax.swing.JLabel lblEditEmail;
    private javax.swing.JLabel lblEditFirstname;
    private javax.swing.JLabel lblEditLastname;
    private javax.swing.JLabel lblEditPassword;
    private javax.swing.JLabel lblEditPayrate;
    private javax.swing.JLabel lblEditShiftDuration;
    private javax.swing.JLabel lblRemoveID;
    private javax.swing.JLabel lblSearchID;
    private javax.swing.JLabel lblidToEdit;
    private javax.swing.JLabel lbllAddLastName;
    private javax.swing.JPanel removePanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtAddFirstName;
    private javax.swing.JTextField txtAddLastName;
    private javax.swing.JTextField txtAddPassword;
    private javax.swing.JTextField txtAddPayrate;
    private javax.swing.JTextArea txtAreaShowAll;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditFirstname;
    private javax.swing.JTextField txtEditLastname;
    private javax.swing.JTextField txtEditPassword;
    private javax.swing.JTextField txtEditPayrate;
    private javax.swing.JTextField txtEditShiftDuration;
    private javax.swing.JTextField txtIDToEdit;
    private javax.swing.JTextField txtIDToRemove;
    private javax.swing.JTextField txtIdToSearch;
    private javax.swing.JPanel viewAllPanel;
    // End of variables declaration//GEN-END:variables
}
